apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dz7-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ittori21/dz5.git'
    targetRevision: main
    path: helm/database
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dz7-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ittori21/dz5.git'
    targetRevision: main
    path: helm/backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dz7-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ittori21/dz5.git'
    targetRevision: main
    path: helm/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
