---
- name: Deploy K3s, Helm, ArgoCD and App
  hosts: k8s_node
  become: yes
  tasks:
    - name: Install K3s (Lightweight Kubernetes)
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s to be ready
      pause:
        seconds: 15

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Create ArgoCD namespace
      shell: k3s kubectl create namespace argocd --dry-run=client -o yaml | k3s kubectl apply -f -

    - name: Install ArgoCD via Helm
      shell: |
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update
        helm upgrade --install argocd argo/argo-cd --namespace argocd --set server.service.type=NodePort

    - name: Deploy Application via ArgoCD GitOps
      shell: |
        export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
        k3s kubectl apply -f https://raw.githubusercontent.com/Ittori21/dz5/main/k3s/argocd-apps.yaml
      ignore_errors: yes
